# https://travis-ci.org/kanasimi/CeJS
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# http://lint.travis-ci.org/
language: node_js
node_js:
  - "4"
#  - "4.1"
#  - "0.12"
# FreeBSD ports node-devel
  - "0.11"
install:
  - npm install
